### ISSUE TITLE
setStartDate(); doesn't change shown date

### ISSUE THREAD

**Issue by MindFlare56** [psinetron/slycalendarview#2]
Let's start positive this time because I enjoy your work here!
But something goes really wrong.

So here's what happens when I change the start date in the listener, so when I save, in the debug I see the selectedStartDate changed but not the shown date. Then if I click back on the calendar icon that displays the dialog the change is not made. So I have to create it back in order to change the date and it doesn't instantly show the change.

@Override
public void onDataSelected(Calendar firstDate, Calendar secondDate, int hours, int minutes) {
       slyCalendarDialog.setStartDate(DateTime.calendarToDate(firstDate));
}

---------------------
Also, I noticed that you use Date in the SlyClandar at some place instead of Calendar. I recommend you to change it to fully support Calendar instead of Date since it is deprecated! Also had to convert the Calendar back to Date witch make no sense. So I suggest you to change it or at least fully support Calendar in order to keep it clean or at least milliSeconds value. Also support to raw String date would be useful since when you pick data from a database, for example, it is returned as a string, not a Calendar. I know that you can simply convert with something like this 
(   calendar.setTime(getSimpleDateFormat().parse(stringDate));    ) but still.

Thank you for your time!

**Comment by psinetron** [comment]
Ok. Will fix at next release
